-- CreateTable
CREATE TABLE "RecommendationConfig" (
    "key" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "activeVariant" TEXT NOT NULL DEFAULT 'A',
    "abEnabled" BOOLEAN NOT NULL DEFAULT false,
    "abRolloutPercent" INTEGER NOT NULL DEFAULT 50,
    "weightUnquotedA" INTEGER NOT NULL DEFAULT 140,
    "weightUnquotedB" INTEGER NOT NULL DEFAULT 160,
    "weightQuoteableA" INTEGER NOT NULL DEFAULT 100,
    "weightQuoteableB" INTEGER NOT NULL DEFAULT 90,
    "weightSoonDeadlineA" INTEGER NOT NULL DEFAULT 70,
    "weightSoonDeadlineB" INTEGER NOT NULL DEFAULT 85,
    "weightUrgentA" INTEGER NOT NULL DEFAULT 80,
    "weightUrgentB" INTEGER NOT NULL DEFAULT 90,
    "weightHighA" INTEGER NOT NULL DEFAULT 50,
    "weightHighB" INTEGER NOT NULL DEFAULT 55,
    "weightCategoryMatchA" INTEGER NOT NULL DEFAULT 60,
    "weightCategoryMatchB" INTEGER NOT NULL DEFAULT 75,
    "weightStateMatchA" INTEGER NOT NULL DEFAULT 40,
    "weightStateMatchB" INTEGER NOT NULL DEFAULT 45,
    "weightRecencyMaxBoostA" INTEGER NOT NULL DEFAULT 30,
    "weightRecencyMaxBoostB" INTEGER NOT NULL DEFAULT 25,
    "weightBidCrowdingPenaltyA" INTEGER NOT NULL DEFAULT 8,
    "weightBidCrowdingPenaltyB" INTEGER NOT NULL DEFAULT 10,
    "bidCrowdingPenaltyCapA" INTEGER NOT NULL DEFAULT 48,
    "bidCrowdingPenaltyCapB" INTEGER NOT NULL DEFAULT 60,
    "categoryWhitelist" JSONB,
    "categoryBlacklist" JSONB,
    "nonWhitelistPenalty" INTEGER NOT NULL DEFAULT 40,
    "blacklistPenalty" INTEGER NOT NULL DEFAULT 180,
    "whitelistBoost" INTEGER NOT NULL DEFAULT 20,
    "attorneyExposureSoftCap" INTEGER NOT NULL DEFAULT 8,
    "attorneyExposurePenaltyPerExtra" INTEGER NOT NULL DEFAULT 20,
    "highRiskPenalty" INTEGER NOT NULL DEFAULT 120,
    "highRiskRuleHitThreshold" INTEGER NOT NULL DEFAULT 1,
    "highRiskReportThreshold" INTEGER NOT NULL DEFAULT 1,
    "highRiskDisputeThreshold" INTEGER NOT NULL DEFAULT 1,
    "maxPerCategoryInTopN" INTEGER NOT NULL DEFAULT 4,
    "categoryExposureWindow" INTEGER NOT NULL DEFAULT 12,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecommendationConfig_pkey" PRIMARY KEY ("key")
);
